application: evaericssonlcsw
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|txt))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|txt))

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: evaericsson.py


